import test from 'node:test';
import assert from 'node:assert/strict';
import { Store } from '../lib/store.mjs';
import { Integrations } from '../lib/integrations.mjs';
import { ApprenticeData,digest } from '../lib/apprentice-data.mjs';
import { MailObserver,ACCOUNT,decodeMail } from '../lib/apprentice-mail.mjs';
const ID='99999999999999999999';
const msg=(id,thread='thread1',labels=['INBOX'],text='Fictional question')=>({id,threadId:thread,labelIds:labels,internalDate:String(Date.now()-10000),payload:{mimeType:'text/plain',headers:[{name:'From',value:labels.includes('SENT')?ACCOUNT:'fictional@example.test'},{name:'To',value:ACCOUNT},{name:'Subject',value:'Fictional rental conversation'}],body:{data:Buffer.from(text).toString('base64url')}}});
function setup(t,handler){const s=new Store(),calls=[],i=new Integrations(s,{OWNER_PASSWORD:'Fictional-test-only-password',INTEGRATION_ENCRYPTION_KEY:Buffer.alloc(32,8).toString('base64')},async(url,o)=>{const u=new URL(url);calls.push(u);if(u.pathname.endsWith('/profile'))return {status:200,data:{emailAddress:ACCOUNT,historyId:ID}};if(u.pathname.endsWith('/labels'))return {status:200,data:{labels:[{id:'private',name:'Friendly/Private'}]}};return handler(u,o);});i.gmailToken=async()=> 'fake-token';s.set('settings',{mode:'shadow',paused:false,useAI:false});const d=new ApprenticeData(s,i);s.set('ap:settings',{...d.settings(),observing:true});const m=new MailObserver(d,i);t.after(async()=>{await m.stop();s.close();});return {s,i,d,m,calls};}
const history=(s,cursor=ID)=>s.set('ap:mail',{phase:'history',cursor,since:new Date(Date.now()-86400000).toISOString(),backfillComplete:true});
const addHistory=ids=>({status:200,data:{historyId:ID+'1',history:[{messagesAdded:ids.map(id=>({message:{id}}))}]}});
test('inbox and sent replies form one case; drafts and automated authors are explicit',async t=>{const f=setup(t,u=>{if(u.pathname.endsWith('/messages'))return {status:200,data:{messages:['in','sent','draft','auto'].map(id=>({id}))}};const id=u.pathname.split('/').pop(),m=msg(id,'thread1',id==='in'?['INBOX']:id==='draft'?['DRAFT']:['SENT']);if(id==='auto')m.payload.headers.push({name:'Auto-Submitted',value:'auto-generated'});return {status:200,data:m};});await f.m.sync();assert.equal(f.d.list().length,1);const sources=f.d.sources(f.d.list()[0].id);assert.equal(sources.length,3);assert.equal(sources.find(x=>x.payload.messageId==='sent').payload.humanConfirmed,false);assert.equal(sources.find(x=>x.payload.messageId==='auto').payload.automated,true);assert(!sources.some(x=>x.payload.direction==='draft'));assert.equal(f.s.get('ap:mail').cursor,ID);});
test('exact mailbox identity checked before any message is read',async t=>{const f=setup(t,()=>{throw new Error('No content permitted');});f.i.request=async u=>u.endsWith('/profile')?{status:200,data:{emailAddress:'other@example.test',historyId:'1'}}:assert.fail('Unexpected content read');await assert.rejects(f.m.sync(),/exact Friendly/);assert.equal(f.d.list().length,0);assert(f.m.status().lastError);});
test('initial history anchor survives paginated backfill; final cursor preserves large IDs',async t=>{const f=setup(t,u=>{if(u.pathname.endsWith('/messages'))return {status:200,data:u.searchParams.has('pageToken')?{messages:[{id:'m2'}]}:{messages:[{id:'m1'}],nextPageToken:'next'}};if(u.pathname.endsWith('/history')){assert.equal(u.searchParams.get('startHistoryId'),ID);return {status:200,data:{historyId:ID+'2'}};}return {status:200,data:msg(u.pathname.split('/').pop())};});await f.m.sync();assert.equal(f.s.get('ap:mail').phase,'backfill');assert.equal(f.s.get('ap:mail').cursor,undefined);await f.m.sync();assert.equal(f.s.get('ap:mail').cursor,ID);await f.m.sync();assert.equal(f.s.get('ap:mail').cursor,ID+'2');assert(f.m.status().lastSync);});
test('mid-batch failure resumes at failed message, without duplicate case or early cursor',async t=>{let fail=true;const f=setup(t,u=>{if(u.pathname.endsWith('/history'))return addHistory(['m1','m2']);const id=u.pathname.split('/').pop();return id==='m2'&&fail?{status:503}:{status:200,data:msg(id)};});history(f.s);await assert.rejects(f.m.sync(),/message could not/);assert.equal(f.s.get('ap:mail').cursor,ID);assert.deepEqual(f.s.get('ap:mail').pending,['m2']);fail=false;await f.m.sync();assert.equal(f.d.sources(f.d.list()[0].id).length,2);assert.equal(f.s.get('ap:mail').cursor,ID+'1');});
test('expired history has explicit gap and bounded recovery',async t=>{let expired=true;const f=setup(t,u=>u.pathname.endsWith('/history')?{status:expired?404:200,data:{historyId:ID+'2'}}:{status:200,data:{messages:[]}});history(f.s);await assert.rejects(f.m.sync(),/expired/);assert.equal(f.m.status().gapDetected,true);assert.equal(f.s.get('ap:mail').phase,'recover');expired=false;await f.m.sync();assert.equal(f.s.get('ap:mail').phase,'history');assert.equal(f.m.status().gapDetected,true);assert(f.m.status().initialSince);});
test('label-only changes keep sent human attribution without auto-queuing teamwork',async t=>{const mail=msg('s','thread1',['SENT']);const f=setup(t,u=>u.pathname.endsWith('/history')?addHistory(['s']):{status:200,data:mail});history(f.s);f.s.set('ap:settings',{...f.d.settings(),autoReview:true});await f.m.sync();const c=f.d.list()[0],source=f.d.sources(c.id)[0],rev=c.revision;f.d.db.prepare('UPDATE ap_sources SET payload=? WHERE id=?').run(f.d.pack({...source.payload,humanConfirmed:true,humanAuthor:'Nicole'},false),source.id);mail.labelIds.push('STARRED');await f.m.sync();assert.equal(f.d.row(c.id).revision,rev);assert.equal(f.d.sources(c.id)[0].payload.humanAuthor,'Nicole');assert.equal(f.d.db.prepare('SELECT COUNT(*) AS n FROM ap_jobs').get().n,0);});
test('saved draft replacement does not delete or suppress the whole thread',async t=>{let cycle=0;const f=setup(t,u=>{if(u.pathname.endsWith('/history'))return addHistory(cycle?['old','new','sent']:['old']);const id=u.pathname.split('/').pop();if(cycle&&id==='old')return {status:404};return {status:200,data:msg(id,'thread1',id==='sent'?['SENT']:['DRAFT'])};});history(f.s);f.s.set('ap:settings',{...f.d.settings(),includeDrafts:true});await f.m.sync();const id=f.d.list()[0].id;cycle=1;await f.m.sync();assert.equal(f.d.list()[0].id,id);assert.equal(f.d.sources(id).length,2);assert(f.d.sources(id).some(x=>x.payload.direction==='sent'));assert.equal(f.d.db.prepare('SELECT COUNT(*) AS n FROM ap_suppression').get().n,0);});
test('privacy label erases existing case and prevents reimport',async t=>{let privateLabel=false;const f=setup(t,u=>u.pathname.endsWith('/history')?addHistory(['m']):{status:200,data:msg('m','thread1',privateLabel?['INBOX','private']:['INBOX'])});history(f.s);await f.m.sync();assert.equal(f.d.list().length,1);privateLabel=true;await f.m.sync();assert.equal(f.d.list().length,0);privateLabel=false;await f.m.sync();assert.equal(f.d.list().length,0);});
test('pause after provider response prevents source storage and cursor advancement',async t=>{let f;f=setup(t,u=>{if(u.pathname.endsWith('/history'))return addHistory(['m']);f.s.set('settings',{mode:'shadow',paused:true});return {status:200,data:msg('m')};});history(f.s);await assert.rejects(f.m.sync(),{name:'AbortError'});assert.equal(f.d.list().length,0);assert.equal(f.s.get('ap:mail').cursor,ID);});
test('history pagination and batch limit retain unfinished delta IDs',async t=>{const ids=Array.from({length:30},(_,i)=>'m'+i);const f=setup(t,u=>u.pathname.endsWith('/history')?addHistory(ids):{status:200,data:msg(u.pathname.split('/').pop())});history(f.s);const a=await f.m.sync();assert.equal(a.processed,25);assert.equal(f.s.get('ap:mail').pending.length,5);assert.equal(f.s.get('ap:mail').cursor,ID);await f.m.sync();assert.equal(f.s.get('ap:mail').cursor,ID+'1');assert.equal(f.d.sources(f.d.list()[0].id).length,30);});
test('mail decoding never executes HTML and preserves preview limitation',()=>{const m=msg('x');delete m.payload.body;m.snippet='<img src=x onerror=bad()> preview';assert.equal(decodeMail(m).message,m.snippet);assert.match(decodeMail(m).limitation,/Preview only/);m.payload.headers.push({name:'Subject',value:'unused'});m.payload.headers.find(x=>x.name==='Subject').value='[SC] Quote';assert.equal(decodeMail(m).locationReviewNeeded,true);});
test('authorization failure is reported with backoff instead of an invisible worker death',async t=>{const f=setup(t,()=>assert.fail('No read'));f.i.gmailToken=async()=>{throw new Error('private secret should not leak');};await assert.rejects(f.m.sync());assert(!f.m.status().lastError.includes('private secret'));assert(f.m.status().nextAttempt);assert.equal(f.m.busy,null);});

test('an excluded new message suppresses the whole known thread before content import',async t=>{let cycle=0;const f=setup(t,u=>u.pathname.endsWith('/history')?addHistory(cycle?['private-new']:['public']):{status:200,data:msg(cycle?'private-new':'public','thread1',cycle?['private']:['INBOX'])});history(f.s);await f.m.sync();assert.equal(f.d.list().length,1);cycle=1;await f.m.sync();assert.equal(f.d.list().length,0);cycle=0;await f.m.sync();assert.equal(f.d.list().length,0);});
