import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID,createHmac } from 'node:crypto';
import { mkdtempSync,rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { Store } from '../lib/store.mjs';
import { Integrations } from '../lib/integrations.mjs';
import { createOffice } from '../server.mjs';
import { Apprenticeship } from '../lib/apprentice-api.mjs';
import { comparison } from '../lib/apprentice-worker.mjs';
import { verifyPhoneSignature,validateCall,transcribeAudio } from '../lib/apprentice-phone.mjs';
const env=()=>({OWNER_PASSWORD:'Fictional-apprentice-test-only',INTEGRATION_ENCRYPTION_KEY:Buffer.alloc(32,7).toString('base64'),NODE_ENV:'development'});
const call=()=>({title:'Fictional consented call',callId:'FIXTURE-'+randomUUID(),provider:'Test bridge',trainer:'Nicole',at:new Date(Date.now()-60000).toISOString(),transcript:'Nicole: What date and delivery address?\nCustomer: I still need to check the venue.',consent:{staff:true,caller:true,businessOnly:true,at:new Date(Date.now()-65000).toISOString(),basis:'Fictional test consent record'}});
function fixture(t,{real=false,request,environment,path}={}){const s=new Store(path),e={...env(),...environment},i=new Integrations(s,e,request||(()=>{throw new Error('Unexpected external request');})),app=createOffice({store:s,env:e,integrations:i,worker:false});s.set('settings',{mode:real?'shadow':'practice',paused:false,useAI:false});t.after(()=>app.close());return {app,a:app.apprenticeship,d:app.apprenticeship.data,s,i,e};}
const route=(a,path,b={})=>a.route('POST','/api/apprentice'+path,null,b);
async function example(a){return (await route(a,'/practice')).caseId;}
async function runCase(a,id){await route(a,'/cases/'+id+'/review',{revision:a.data.row(id).revision});await a.worker.active?.promise;return a.data.detail(id);}

test('apprenticeship migration is idempotent and leaves existing tasks intact',async t=>{const {a,s,i}=fixture(t);const old=s.addTask({title:'Old fictional task',role:'office',source:'practice'});new Apprenticeship(s,i);assert.equal(s.task(old.id).title,'Old fictional task');assert.equal(a.summary().team.length,4);assert.equal(a.summary().businessActionsEnabled,false);});
test('real calls require all three consent attestations',async t=>{const {a,d}=fixture(t,{real:true});for(const key of ['staff','caller','businessOnly']){const b=call();b.consent[key]=false;await assert.rejects(route(a,'/phone',b),/Confirm staff/);}assert.equal(d.list().length,0);});
test('calls require a dated consent basis and a completed-call time',()=>{for(const change of [{at:'not-a-date'},{at:new Date(Date.now()+600000).toISOString()},{consent:{staff:true,caller:true,businessOnly:true,at:'bad',basis:'test'}}])assert.throws(()=>validateCall({...call(),...change}));});
test('real calls cannot enter practice workspace or unencrypted storage',async t=>{const f=fixture(t);await assert.rejects(route(f.a,'/phone',call()),/shadow/);f.s.set('settings',{mode:'shadow',paused:false});delete f.i.env.INTEGRATION_ENCRYPTION_KEY;await assert.rejects(route(f.a,'/phone',call()),/encryption key/);assert.equal(f.d.list().length,0);});
test('real phone transcripts are encrypted and duplicate deliveries are idempotent',async t=>{const {a,d}=fixture(t,{real:true});const b=call(),first=await route(a,'/phone',b),rev=d.row(first.caseId).revision,second=await route(a,'/phone',b);assert.equal(first.caseId,second.caseId);assert.equal(second.changed,false);assert.equal(d.row(first.caseId).revision,rev);assert.equal(d.sources(first.caseId).length,1);const raw=d.db.prepare('SELECT payload FROM ap_sources').get().payload;assert(raw.startsWith('enc:'));assert(!raw.includes('Nicole:'));assert(!JSON.stringify(a.summary()).includes(env().OWNER_PASSWORD));});
test('fictional example uses no provider and teamwork stays in one case',async t=>{const {a,d}=fixture(t);const id=await example(a),result=await runCase(a,id);assert.equal(result.status,'review');assert.equal(result.notes.filter(n=>n.kind==='question').length,3);assert.equal(result.notes.filter(n=>n.kind==='contribution').length,3);assert.equal(result.draftHistory.length,1);assert.equal(result.decisions.length,0);assert.equal(d.list().length,1);assert(result.draft.includes('CHECKLIST MODE'));});
test('concurrent reviews of the same case are rejected',async t=>{const {a,s,d}=fixture(t);const id=await example(a);s.set('settings',{mode:'practice',paused:true});await route(a,'/cases/'+id+'/review',{revision:d.row(id).revision});await assert.rejects(route(a,'/cases/'+id+'/review',{revision:d.row(id).revision}),/already/);assert.equal(d.db.prepare('SELECT COUNT(*) AS n FROM ap_jobs').get().n,1);});
test('model-assisted inter-agent review has three consultations and one synthesis, no tools',async t=>{const calls=[];const f=fixture(t,{real:true,environment:{OPENAI_API_KEY:'fake-model-key',OPENAI_MODEL:'test-model'},request:async(url,o)=>{calls.push({url,body:JSON.parse(o.body)});return {status:200,data:{status:'completed',output:[{type:'message',content:[{type:'output_text',text:'Fixture evidence review '+calls.length}]}],usage:{total_tokens:10}}};}});f.s.set('settings',{mode:'shadow',paused:false,useAI:true});const id=(await route(f.a,'/phone',call())).caseId;await runCase(f.a,id);assert.equal(calls.length,4);assert(calls.every(c=>c.url==='https://api.openai.com/v1/responses'&&!c.body.tools));assert.equal(f.s.snapshot().usage.calls,4);assert.equal(f.d.detail(id).notes.filter(n=>n.kind==='contribution').length,3);});
test('global pause aborts an in-flight consultation and prevents follow-up model calls',async t=>{let started;const ready=new Promise(r=>started=r);let n=0;const f=fixture(t,{real:true,environment:{OPENAI_API_KEY:'fake-key',OPENAI_MODEL:'test'},request:(url,o)=>{n++;started();return new Promise((r,j)=>o.signal.addEventListener('abort',()=>j(new DOMException('aborted','AbortError')),{once:true}));}});f.s.set('settings',{mode:'shadow',paused:false,useAI:true});const id=(await route(f.a,'/phone',call())).caseId;await route(f.a,'/cases/'+id+'/review',{revision:f.d.row(id).revision});await ready;f.s.set('settings',{mode:'shadow',paused:true,useAI:true});f.a.pause();await f.a.worker.active?.promise;assert.equal(n,1);assert.equal(f.d.row(id).status,'blocked');assert.equal(f.d.detail(id).draft,'');});
test('changed evidence invalidates an in-flight result instead of approving stale work',async t=>{let f;f=fixture(t,{real:true,environment:{OPENAI_API_KEY:'fake-key',OPENAI_MODEL:'test'},request:async()=>{const id=f.d.list()[0].id;f.d.ingest(id,{key:'new-evidence',kind:'phone',payload:{message:'New information'}});return {status:200,data:{output:[{type:'message',content:[{type:'output_text',text:'Obsolete answer'}]}]}};}});f.s.set('settings',{mode:'shadow',paused:false,useAI:true});const id=(await route(f.a,'/phone',call())).caseId;await runCase(f.a,id);assert.equal(f.d.row(id).status,'blocked');assert.equal(f.d.detail(id).draft,'');});
test('daily provider budget stops collaboration without automatic paid retry',async t=>{let n=0;const f=fixture(t,{real:true,environment:{OPENAI_API_KEY:'fake-key',OPENAI_MODEL:'test',MAX_DAILY_AI_CALLS:'1'},request:async()=>{n++;return {status:200,data:{output:[{type:'message',content:[{type:'output_text',text:'Fixture response'}]}]}};}});f.s.set('settings',{mode:'shadow',paused:false,useAI:true});const id=(await route(f.a,'/phone',call())).caseId;await runCase(f.a,id);assert.equal(n,1);assert.equal(f.d.row(id).status,'blocked');assert.match(f.d.row(id).reason,/budget/);});
test('per-employee pause holds teamwork until that employee is available',async t=>{const {a,s,d}=fixture(t);const id=await example(a);s.set('ap:agent:email',{paused:true});await route(a,'/cases/'+id+'/review',{revision:d.row(id).revision});assert.equal(a.worker.active,null);s.set('ap:agent:email',{paused:false});a.worker.tick();await a.worker.active?.promise;assert.equal(d.row(id).status,'review');});
test('one final draft is approved exactly, and a source change requires a new review',async t=>{const {a,d}=fixture(t);const id=await example(a),c=await runCase(a,id);await route(a,'/cases/'+id+'/approve',{revision:c.revision,draft:'Exact owner-corrected draft'});assert.equal(d.detail(id).decisions[0].content,'Exact owner-corrected draft');assert.equal(d.row(id).status,'approved');d.ingest(id,{key:'more-source',kind:'phone',payload:{message:'New detail'}});await assert.rejects(route(a,'/cases/'+id+'/approve',{revision:c.revision,draft:'Old'}),/changed/);assert.equal(d.detail(id).draftHistory.length,1);assert.equal(d.detail(id).draft,'');});
test('peer messages cannot cite unrelated case evidence',async t=>{const {a,d}=fixture(t);const id=await example(a);assert.throws(()=>d.note(id,'email','office','question','Check this',[randomUUID()]),/Evidence must belong/);});
test('pending placeholders and exceptions never become permanent policy',async t=>{const {a,d,s}=fixture(t);const id=await example(a);await runCase(a,id);const l=d.lessons(id)[0],before=s.rules().filter(r=>r.status==='approved').length;await assert.rejects(route(a,'/lessons/'+l.id+'/decide',{revision:l.revision,decision:'approved'}),/actual lesson/);await route(a,'/lessons/'+l.id+'/decide',{revision:l.revision,decision:'exception'});assert.equal(s.rules().filter(r=>r.status==='approved').length,before);});
test('practice lesson approval is isolated from the real handbook',async t=>{const {a,d,s}=fixture(t);const id=await example(a);await runCase(a,id);const l=d.lessons(id)[0];await route(a,'/lessons/'+l.id+'/decide',{revision:l.revision,decision:'approved',body:'Fictional example procedure only.'});assert(!s.rules().some(r=>r.body==='Fictional example procedure only.'));});
test('real lesson approval and revocation are explicit, revision checked and source-linked',async t=>{const {a,d,s}=fixture(t,{real:true});const id=(await route(a,'/phone',call())).caseId;const l=d.propose(id,{revision:d.row(id).revision,title:'Check details',body:'Confirm the address before a delivery commitment.'});await route(a,'/lessons/'+l+'/decide',{revision:1,decision:'approved'});const rule=s.rules().find(r=>r.title==='Check details');assert.equal(rule.status,'approved');await assert.rejects(route(a,'/lessons/'+l+'/decide',{revision:1,decision:'revoked'}),/changed/);await route(a,'/lessons/'+l+'/decide',{revision:2,decision:'revoked'});assert.equal(s.rules().find(r=>r.id===rule.id).status,'revoked');});
test('erasure removes case content, revokes linked policy and prevents reimport',async t=>{const {a,d,s}=fixture(t,{real:true});const b=call(),id=(await route(a,'/phone',b)).caseId;const l=d.propose(id,{revision:d.row(id).revision,title:'Private example',body:'Approved fixture handling.'});await route(a,'/lessons/'+l+'/decide',{revision:1,decision:'approved'});d.remove(id);assert.equal(d.list().length,0);assert.equal(d.db.prepare('SELECT COUNT(*) AS n FROM ap_sources').get().n,0);assert((await route(a,'/phone',b)).excluded);assert(!s.rules().some(r=>r.body==='Approved fixture handling.'));});
test('transcript corrections invalidate drafts and redact payment-like strings',async t=>{const {a,d}=fixture(t,{real:true});const id=(await route(a,'/phone',call())).caseId,c=await runCase(a,id);await route(a,'/cases/'+id+'/edit-transcript',{revision:c.revision,sourceId:c.sources[0].id,message:'Nicole: card 4111 1111 1111 1111 removed; ask for address.'});const next=d.detail(id);assert.equal(next.status,'open');assert(!next.sources[0].payload.message.includes('4111'));assert.equal(next.draft,'');});
test('signed phone deliveries reject altered content, stale timestamps and missing consent',async t=>{const {a,d,s,i}=fixture(t,{real:true});i.env.PHONE_WEBHOOK_SECRET='Fictional-only-phone-signing-key-32-plus';s.set('ap:settings',{...d.settings(),phoneWebhook:true});const b={...call(),eventId:'event-1'},raw=Buffer.from(JSON.stringify(b)),ts=String(Math.floor(Date.now()/1000));const sign=buf=>({'x-office-timestamp':ts,'x-office-signature':'sha256='+createHmac('sha256',i.env.PHONE_WEBHOOK_SECRET).update(ts+'.').update(buf).digest('hex')});assert.throws(()=>verifyPhoneSignature(Buffer.from('bad'),sign(raw),i.env.PHONE_WEBHOOK_SECRET),/rejected/);assert.throws(()=>verifyPhoneSignature(raw,sign(raw),i.env.PHONE_WEBHOOK_SECRET,Date.now()+600000),/rejected/);const first=await a.webhook(raw,sign(raw),b);assert(first.caseId);assert((await a.webhook(raw,sign(raw),b)).duplicate);assert.equal(d.sources(first.caseId).length,1);const no={...call(),eventId:'event-2'};no.consent.caller=false;const noRaw=Buffer.from(JSON.stringify(no));await assert.rejects(a.webhook(noRaw,sign(noRaw),no),/Confirm staff/);assert.equal(d.db.prepare('SELECT COUNT(*) AS n FROM ap_receipts').get().n,1);});
test('comparison never claims a retrospective answer predicted a sent reply',()=>{const sources=[{id:'i',kind:'email',payload:{direction:'incoming',at:'2026-09-21T10:00:00Z',message:'Question'}},{id:'s',kind:'email',payload:{direction:'sent',at:'2026-09-21T10:05:00Z',message:'Answer',humanConfirmed:true}}];assert.equal(comparison(sources,[{created:'2026-09-21T10:06:00Z',body:'Later'}]).aiBeforeReply,null);assert.equal(comparison(sources,[{created:'2026-09-21T10:03:00Z',body:'Earlier'}]).aiBeforeReply.body,'Earlier');sources[1].payload.humanConfirmed=false;assert.equal(comparison(sources).human,null);});
test('restarting with durable casework marks interrupted runs blocked',async()=>{const dir=mkdtempSync(join(tmpdir(),'ap-restart-'));let s=new Store(join(dir,'db')),i=new Integrations(s,env()),a=new Apprenticeship(s,i);const c=a.data.create({key:'test-restart',title:'Fictional restart',practice:true,lead:'phone'});a.data.ingest(c.id,{key:'test-source',kind:'phone',payload:{message:'Fictional'}});a.data.enqueue(c.id,{revision:a.data.row(c.id).revision});s.db.prepare("UPDATE ap_jobs SET status='running'").run();s.db.prepare("UPDATE ap_cases SET status='working'").run();s.close();s=new Store(join(dir,'db'));i=new Integrations(s,env());a=new Apprenticeship(s,i);assert.equal(a.data.row(c.id).status,'blocked');assert.equal(a.data.sources(c.id).length,1);s.close();rmSync(dir,{recursive:true});});
test('audio requires explicit provider permission and supported bounded content',async t=>{const {i}=fixture(t,{real:true});const b={...call(),audio:Buffer.from('not an audio file at all').toString('base64'),providerConsent:true,sensitiveContentRemoved:true};await assert.rejects(transcribeAudio(b,i,new AbortController().signal),/Configure/);i.env.OPENAI_API_KEY='fake';i.env.OPENAI_TRANSCRIBE_MODEL='test';await assert.rejects(transcribeAudio({...b,providerConsent:false},i,new AbortController().signal),/Confirm permission/);await assert.rejects(transcribeAudio(b,i,new AbortController().signal),/WAV/);});
test('fictional approved examples cannot enter a real model context',async t=>{const calls=[];const f=fixture(t,{environment:{OPENAI_API_KEY:'fake-key',OPENAI_MODEL:'fixture'},request:async(url,o)=>{calls.push(o.body);return {status:200,data:{output:[{type:'message',content:[{type:'output_text',text:'Grounded fixture only'}]}]}};}});const id=await example(f.a),l=f.d.propose(id,{revision:f.d.row(id).revision,title:'Fictional pattern',body:'FORBIDDEN_FICTIONAL_EXAMPLE'});f.d.decideLesson(l,{revision:1,decision:'approved'});f.s.set('settings',{mode:'shadow',paused:false,useAI:true});const real=(await route(f.a,'/phone',call())).caseId;await runCase(f.a,real);assert.equal(calls.length,4);assert(calls.every(x=>!x.includes('FORBIDDEN_FICTIONAL_EXAMPLE')));});
test('transcript corrections survive original provider replay and block conflicting new versions',async t=>{const f=fixture(t,{real:true}),b=call(),id=(await route(f.a,'/phone',b)).caseId,source=f.d.sources(id)[0];await route(f.a,'/cases/'+id+'/edit-transcript',{revision:f.d.row(id).revision,sourceId:source.id,message:'Nicole: Owner-corrected transcript.'});assert.equal((await route(f.a,'/phone',b)).changed,false);assert.equal(f.d.sources(id)[0].payload.message,'Nicole: Owner-corrected transcript.');await assert.rejects(route(f.a,'/phone',{...b,transcript:'Different provider text'}),/corrected by the owner/);});
test('audio success is bounded multipart, counted, and does not store a recording or start a case',async t=>{const calls=[];const f=fixture(t,{real:true,environment:{OPENAI_API_KEY:'fake',OPENAI_TRANSCRIBE_MODEL:'gpt-4o-transcribe-diarize'},request:async(url,o)=>{calls.push({url,body:o.body.toString()});return {status:200,data:{segments:[{start:1,speaker:'A',text:'What is the event date?'}]}};}});const audio=Buffer.alloc(44);audio.write('RIFF');audio.write('WAVE',8);const r=await route(f.a,'/audio',{...call(),audio:audio.toString('base64'),providerConsent:true,sensitiveContentRemoved:true});assert.match(r.transcript,/Speaker A/);assert.equal(calls.length,1);assert.match(calls[0].url,/audio\/transcriptions$/);assert.match(calls[0].body,/diarized_json/);assert.equal(f.s.snapshot().usage.calls,1);assert.equal(f.d.list().length,0);});
