import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID,createHmac } from 'node:crypto';
import { createOffice } from '../server.mjs';
import { Store } from '../lib/store.mjs';
const env={NODE_ENV:'development',OWNER_PASSWORD:'Fictional-browser-test-owner',INTEGRATION_ENCRYPTION_KEY:Buffer.alloc(32,9).toString('base64'),PHONE_WEBHOOK_SECRET:'Fictional-phone-secret-for-test-only'};
async function http(t){const store=new Store(),app=createOffice({store,env,worker:false});await new Promise(r=>app.server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+app.server.address().port;t.after(()=>app.close());const login=await fetch(origin+'/api/login',{method:'POST',headers:{origin,'content-type':'application/json'},body:JSON.stringify({password:env.OWNER_PASSWORD})}),cookie=login.headers.get('set-cookie').split(';')[0];assert.equal(login.status,200);let state=await(await fetch(origin+'/api/state',{headers:{cookie}})).json();const post=(path,body,headers={})=>fetch(origin+path,{method:'POST',headers:{origin,'content-type':'application/json',cookie,'x-csrf-token':state.csrf,...headers},body:JSON.stringify(body)});return {app,store,origin,cookie,post,state};}
test('apprenticeship private routes require login and CSRF; static modules are allowed',async t=>{const f=await http(t);for(const path of ['/api/apprentice','/api/apprentice/cases','/api/apprentice/lessons'])assert.equal((await fetch(f.origin+path)).status,401);for(const path of ['/apprentice-views.js','/apprentice-case.js']){const r=await fetch(f.origin+path);assert.equal(r.status,200);assert.match(r.headers.get('content-type'),/javascript/);}assert.equal((await f.post('/api/apprentice/practice',{}, {'x-csrf-token':'wrong'})).status,403);assert.equal((await f.post('/api/apprentice/practice',{}, {origin:'https://wrong.test'})).status,403);assert.equal((await fetch(f.origin+'/lib/apprentice-data.mjs')).status,404);});
test('HTTP case workflow saves one reviewed draft, protected detail and audit',async t=>{const f=await http(t);let r=await f.post('/api/apprentice/practice',{});const id=(await r.json()).caseId;const detail=()=>fetch(f.origin+'/api/apprentice/cases/'+id,{headers:{cookie:f.cookie}}).then(r=>r.json());const c=await detail();assert.equal(c.practice,true);await f.post('/api/settings',{paused:false});r=await f.post('/api/apprentice/cases/'+id+'/review',{revision:c.revision});assert.equal(r.status,200);await f.app.apprenticeship.worker.active?.promise;const reviewed=await detail();assert.equal(reviewed.status,'review');assert.equal(reviewed.notes.filter(x=>x.kind==='summary').length,1);r=await f.post('/api/apprentice/cases/'+id+'/approve',{revision:reviewed.revision,draft:'HTTP owner-approved text'});assert.equal(r.status,200);assert.equal((await r.json()).sent,false);const summary=await(await fetch(f.origin+'/api/state',{headers:{cookie:f.cookie}})).text();assert(!summary.includes('HTTP owner-approved text'));assert(!summary.includes(env.INTEGRATION_ENCRYPTION_KEY));assert.equal((await fetch(f.origin+'/api/apprentice/cases/'+id)).status,401);});
test('phone hook rejects unauthorized payload and requires separate explicit enablement',async t=>{const f=await http(t);const path='/api/apprentice/phone-hook';assert.equal((await fetch(f.origin+path,{method:'POST',headers:{'content-type':'application/json'},body:'{}'})).status,403);await f.post('/api/settings',{mode:'shadow',paused:false});assert.equal((await f.post('/api/apprentice/settings',{phoneWebhook:true})).status,400);assert.equal((await f.post('/api/apprentice/settings',{phoneWebhook:true,consent:true})).status,200);const body=JSON.stringify({eventId:randomUUID(),callId:'test-call',provider:'Mock bridge',trainer:'Nicole',at:new Date(Date.now()-10000).toISOString(),transcript:'Fictional transcript only',consent:{staff:true,caller:true,businessOnly:true,at:new Date(Date.now()-20000).toISOString(),basis:'Fictional test attestation'}}),time=String(Math.floor(Date.now()/1000)),sig='sha256='+createHmac('sha256',env.PHONE_WEBHOOK_SECRET).update(time+'.'+body).digest('hex');const request=signature=>fetch(f.origin+path,{method:'POST',headers:{'content-type':'application/json','x-office-timestamp':time,'x-office-signature':signature},body});assert.equal((await request('bad')).status,401);const r=await request(sig);assert.equal(r.status,200);assert((await r.json()).caseId);assert.equal((await(await request(sig)).json()).duplicate,true);await f.post('/api/settings',{paused:true});assert.equal((await request(sig)).status,409);});
test('private imports and observation are blocked without connections; no outbound write endpoints exist',async t=>{const f=await http(t);assert.equal((await f.post('/api/apprentice/settings',{observing:true,consent:true})).status,409);await f.post('/api/settings',{mode:'shadow',paused:false});assert.equal((await f.post('/api/apprentice/settings',{observing:true,consent:true})).status,400);assert.equal((await f.post('/api/apprentice/send',{})).status,404);assert.equal((await f.post('/api/apprentice/call',{})).status,404);assert.equal((await f.post('/api/apprentice/sync',{})).status,409);assert.equal(f.app.apprenticeship.summary().phone.liveListening,false);});
