import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { Store } from '../lib/store.mjs';
import { Integrations } from '../lib/integrations.mjs';
import { createOffice } from '../server.mjs';
const env={NODE_ENV:'development',OWNER_PASSWORD:'Only-fictional-command-test-123',INTEGRATION_ENCRYPTION_KEY:Buffer.alloc(32,5).toString('base64')};
function setup(t,{shadow=false,request,extra={}}={}){const store=new Store(),e={...env,...extra},i=new Integrations(store,e,request||(()=>assert.fail('Unexpected external request'))),app=createOffice({store,env:e,integrations:i,worker:false});store.set('settings',{mode:shadow?'shadow':'practice',paused:false,useAI:false});t.after(()=>app.close());return {app,s:store,i,c:app.apprenticeship.command,a:app.apprenticeship,d:app.apprenticeship.data};}
const input=(message='Team, what needs my attention?',recipient='team')=>({message,recipient,requestId:randomUUID()});
async function done(a){await a.worker.active?.promise;}
test('owner can address whole team and get an honest saved brief without a model',async t=>{const f=setup(t),r=f.c.submit(input());await done(f.a);const d=f.d.detail(r.caseId);assert.equal(d.status,'review');assert.match(d.draft,/OFFICE BRIEF/);assert.match(d.draft,/not configured/);assert.equal(d.notes.filter(n=>n.kind==='contribution').length,3);assert.equal(f.c.threads().length,1);assert.equal(f.c.snapshot().team.length,4);});
test('private Friendly brain answers casual owner chat naturally with one model call',async t=>{
  const originalFetch=globalThis.fetch,calls=[];
  globalThis.fetch=async(url,options)=>{calls.push({url:String(url),body:JSON.parse(options.body)});return new Response(JSON.stringify({message:{content:'Hey Bryan — I’m here. The team is online. What do you want to work on?'},prompt_eval_count:12,eval_count:18}),{status:200,headers:{'content-type':'application/json'}});};
  t.after(()=>{globalThis.fetch=originalFetch;});
  const f=setup(t,{shadow:true,extra:{AI_BRAIN_URL:'http://fixture.railway.internal:11434',AI_BRAIN_MODEL:'fixture-14b',ENABLE_BUILTIN_AI:'true'}});
  f.s.set('settings',{mode:'shadow',paused:false,useAI:true});
  const r=f.c.submit(input('hi'));await done(f.a);const d=f.d.detail(r.caseId);
  assert.equal(d.status,'open');assert.equal(calls.length,1);assert.match(d.notes.find(n=>n.kind==='summary').body,/Hey Bryan/);
  assert.equal(d.notes.filter(n=>n.kind==='contribution').length,0);assert(!d.notes.some(n=>/CHECKLIST RESPONSE|OWNER CHECKS/.test(n.body)));
  assert.equal(calls[0].body.messages.at(-1).role,'user');assert.match(calls[0].body.messages.at(-1).content,/hi/);
});
test('specific employee receives owner instruction; same conversation supports follow-up',async t=>{const f=setup(t),r=f.c.submit(input('Avery, help me with a reply.','email'));await done(f.a);assert.equal(f.d.row(r.caseId).lead,'email');const b={...input('Riley, what are you waiting for?','phone'),caseId:r.caseId,revision:f.d.row(r.caseId).revision};f.c.submit(b);await done(f.a);const d=f.d.detail(r.caseId);assert.equal(d.lead,'phone');assert.equal(d.sources.filter(s=>s.kind==='owner').length,2);assert.equal(d.draftHistory.length,2);});
test('message request IDs deduplicate transmission and reject altered retries',async t=>{const f=setup(t),b=input(),first=f.c.submit(b),second=f.c.submit(b);assert.equal(second.duplicate,true);assert.equal(second.caseId,first.caseId);assert.throws(()=>f.c.submit({...b,message:'Other'}),/different message/);await done(f.a);assert.equal(f.c.threads().length,1);});
test('owner instructions are encrypted in shadow and source HTML stays data',async t=>{const f=setup(t,{shadow:true}),r=f.c.submit(input('<b>Private owner phrase</b>'));await done(f.a);const raw=f.d.db.prepare("SELECT payload FROM ap_sources WHERE kind='owner'").get().payload;assert(raw.startsWith('enc:'));assert(!raw.includes('Private owner phrase'));assert(f.c.snapshot().feed.some(n=>n.body.includes('<b>Private owner phrase</b>')));assert(!JSON.stringify(f.c.snapshot()).includes(env.INTEGRATION_ENCRYPTION_KEY));});
test('paused office keeps requests queued; continuous shift resume does not enable integrations or models',async t=>{const f=setup(t);f.s.set('settings',{mode:'practice',paused:true,useAI:false});const r=f.c.submit(input());assert.equal(r.paused,true);assert.equal(f.d.row(r.caseId).status,'queued');await f.c.route('POST','/api/apprentice/command/settings',{enabled:true,resume:true});f.a.worker.tick();await done(f.a);assert.equal(f.s.get('settings').useAI,false);assert.equal(f.a.data.settings().observing,false);assert.equal(f.a.data.settings().phoneWebhook,false);});
test('standing duties do not read live services in practice',async t=>{const f=setup(t,{extra:{ENABLE_WEBSITE_CHECKS:'true'}});await f.c.tick(true);assert.equal(f.s.get('command:duty:website').status,'waiting');assert.equal(f.d.list().length,0);assert(f.c.heartbeat);});
test('actual website check runs without a paid model and changed reports deduplicate',async t=>{let n=0;const f=setup(t,{shadow:true,extra:{ENABLE_WEBSITE_CHECKS:'true'},request:async()=>{n++;return {status:200,text:'<title>Friendly</title><meta name="viewport" content="width=device-width">',data:null};}});await f.c.tick(true);await f.c.tick(true);assert.equal(n,6);assert.equal(f.d.list().length,1);assert.equal(f.s.get('command:duty:website').status,'checked');assert.equal(f.c.snapshot().duties.length,5);assert.match(f.d.sources(f.d.list()[0].id)[0].payload.message,/Static HTML/);assert.equal(f.s.snapshot().usage.calls,0);});
test('specific owner website request attaches actual evidence and returns report',async t=>{const f=setup(t,{shadow:true,extra:{ENABLE_WEBSITE_CHECKS:'true'},request:async()=>({status:503,text:'unavailable'})});const r=f.c.submit({...input('Alex, check website','tech'),action:'website'});await done(f.a);const d=f.d.detail(r.caseId);assert.equal(d.status,'review');assert.match(d.draft,/503/);assert.match(d.draft,/not a website fix/);});
test('absent order connection is an explicit blocker, not a fabricated booking list',async t=>{const f=setup(t,{shadow:true}),r=f.c.submit({...input('Morgan, review orders','office'),action:'orders'});await done(f.a);assert.match(f.d.detail(r.caseId).draft,/SOURCE BLOCKED/);assert.match(f.d.detail(r.caseId).draft,/No read-only order endpoint/);});
test('owner case rejects stale revision and concurrent follow-up before paid calls',async t=>{const f=setup(t);f.s.set('settings',{mode:'practice',paused:true,useAI:false});const r=f.c.submit(input());assert.throws(()=>f.c.submit({...input('next'),caseId:r.caseId,revision:f.d.row(r.caseId).revision}),/finish/);assert.throws(()=>f.c.submit({...input('next'),caseId:r.caseId,revision:0}),/changed/);});
test('global pause aborts source work and no claimed response is saved',async t=>{let started;const ready=new Promise(r=>started=r);const f=setup(t,{shadow:true,extra:{ENABLE_WEBSITE_CHECKS:'true'},request:async(u,o)=>{started();return new Promise((r,j)=>o.signal.addEventListener('abort',()=>j(new DOMException('Stopped','AbortError'))));}});const r=f.c.submit({...input('Check website','tech'),action:'website'});await ready;f.s.set('settings',{mode:'shadow',paused:true,useAI:false});f.a.pause();await done(f.a);assert.equal(f.d.row(r.caseId).status,'blocked');assert.equal(f.d.detail(r.caseId).draft,'');});
test('no idle agent is labeled working and all four desks expose real current state',async t=>{const f=setup(t);assert(f.c.snapshot().team.every(r=>r.status!=='working'));assert.match(f.c.card('phone').activity,/No live phone/);f.s.set('agent:email',{paused:true});assert.equal(f.c.card('email').status,'paused');});
test('continuous settings persist; privacy erasure removes owner threads and feed',async t=>{const f=setup(t),r=f.c.submit(input());await done(f.a);await f.c.route('POST','/api/apprentice/command/settings',{enabled:false});assert.equal(f.c.settings().enabled,false);assert.equal(f.s.get('settings').paused,true);f.d.remove(r.caseId);assert.equal(f.c.threads().length,0);assert(!f.c.feed().some(n=>n.caseId===r.caseId));});
test('owner endpoint requires login and CSRF and retains narrow microphone policy',async t=>{const f=setup(t);await new Promise(r=>f.app.server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+f.app.server.address().port;assert.equal((await fetch(base+'/api/apprentice/command')).status,401);const login=await fetch(base+'/api/login',{method:'POST',headers:{origin:base,'content-type':'application/json'},body:JSON.stringify({password:env.OWNER_PASSWORD})});const cookie=login.headers.get('set-cookie').split(';')[0];const r=await fetch(base+'/api/apprentice/command/message',{method:'POST',headers:{cookie,origin:base,'content-type':'application/json'},body:JSON.stringify(input())});assert.equal(r.status,403);const state=await fetch(base+'/api/state',{headers:{cookie}});assert.equal(state.headers.get('permissions-policy'),'camera=(), microphone=(self), geolocation=()');});
